version: "3.8"

services:

  ### Anwendung ###

  TimeService:
    image: ghcr.io/jexxa-projects/jexxatutorials/timeservice:latest
    ports:
      - "7502:7502"

    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider 'http://localhost:7502/BoundedContext/isRunning/'"]
      interval: 10s
      timeout: 10s
      retries: 3

    deploy:
      replicas: 2
      update_config:
        order: start-first        # Configure rolling updates
        failure_action: rollback

      rollback_config:
        parallelism: 1            # Rollback config
        order: start-first

      restart_policy:
        condition: on-failure


  ### Infrastruktur ###

  ActiveMQ:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    restart: always
    environment:
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"
      AMQ_EXTRA_ARGS: --relax-jolokia
