name: Merge me!

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Maven Test Build'

jobs:
  merge-me:
    name: Merge me!

    runs-on: ubuntu-latest

    steps:
      - name: Merge me!
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@bdc1160618241c08c6c263e1fad2954773037b9b
        with:
          GITHUB_TOKEN: ${{ secrets.MERGE_ME_SECRET }}
          PRESET: DEPENDABOT_MINOR
